In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tabular-playground-series-aug-2022/sample_submission.csv
/kaggle/input/tabular-playground-series-aug-2022/train.csv
/kaggle/input/tabular-playground-series-aug-2022/test.csv


In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("/kaggle/input/tabular-playground-series-aug-2022/train.csv")

In [4]:
dt = pd.read_csv("/kaggle/input/tabular-playground-series-aug-2022/test.csv")

In [5]:
df.head()

id product_code  loading attribute_0 attribute_1  attribute_2  attribute_3  \
0   0            A    80.10  material_7  material_8            9            5   
1   1            A    84.89  material_7  material_8            9            5   
2   2            A    82.43  material_7  material_8            9            5   
3   3            A   101.07  material_7  material_8            9            5   
4   4            A   188.06  material_7  material_8            9            5   

   measurement_0  measurement_1  measurement_2  ...  measurement_9  \
0              7              8              4  ...         10.672   
1             14              3              3  ...         12.448   
2             12              1              5  ...         12.715   
3             13              2              6  ...         12.471   
4              9              2              8  ...         10.337   

   measurement_10  measurement_11  measurement_12  measurement_13  \
0          15.859          17.594          15.193          15.029   
1          17.947          17.915          11.755          14.732   
2          15.607             NaN          13.798          16.711   
3          16.346          18.377          10.020          15.250   
4          17.082          19.932          12.428          16.182   

   measurement_14  measurement_15  measurement_16  measurement_17  failure  
0             NaN          13.034          14.684         764.100        0  
1          15.425          14.395          15.631         682.057        0  
2          18.631          14.094          17.946         663.376        0  
3          15.562          16.154          17.172         826.282        0  
4          12.760          13.153          16.412         579.885        0  

[5 rows x 26 columns]

In [6]:
df["failure"].nunique()

2

In [7]:
df.tail()

id product_code  loading attribute_0 attribute_1  attribute_2  \
26565  26565            E   158.95  material_7  material_6            6   
26566  26566            E   146.02  material_7  material_6            6   
26567  26567            E   115.62  material_7  material_6            6   
26568  26568            E   106.38  material_7  material_6            6   
26569  26569            E   131.20  material_7  material_6            6   

       attribute_3  measurement_0  measurement_1  measurement_2  ...  \
26565            9              6             16              4  ...   
26566            9             10             12              8  ...   
26567            9              1             10              1  ...   
26568            9              2              9              4  ...   
26569            9              6             19              1  ...   

       measurement_9  measurement_10  measurement_11  measurement_12  \
26565            NaN          12.177          17.942          10.112   
26566         11.242          14.179          20.564          10.234   
26567         11.407          16.437          17.476           8.668   
26568         11.392          17.064          17.814          14.928   
26569         10.611          15.603          19.703          11.006   

       measurement_13  measurement_14  measurement_15  measurement_16  \
26565          15.795          18.572          16.144             NaN   
26566          14.450          14.322          13.146          16.471   
26567          15.069          16.599          15.590          14.065   
26568          16.273          15.485          13.624          12.865   
26569          15.875          13.366          16.527          17.890   

       measurement_17  failure  
26565         729.131        0  
26566         853.924        0  
26567         750.364        0  
26568         730.156        0  
26569         602.354        0  

[5 rows x 26 columns]

In [8]:
dt.head()

id product_code  loading attribute_0 attribute_1  attribute_2  \
0  26570            F   119.57  material_5  material_6            6   
1  26571            F   113.51  material_5  material_6            6   
2  26572            F   112.16  material_5  material_6            6   
3  26573            F   112.72  material_5  material_6            6   
4  26574            F   208.00  material_5  material_6            6   

   attribute_3  measurement_0  measurement_1  measurement_2  ...  \
0            4              6              9              6  ...   
1            4             11              8              0  ...   
2            4              8             12              4  ...   
3            4              8             11             10  ...   
4            4             14             16              8  ...   

   measurement_8  measurement_9  measurement_10  measurement_11  \
0         18.654         10.802          15.909          18.070   
1         19.368         12.032          13.998             NaN   
2         17.774         11.743          17.046          18.086   
3         18.948         11.790          18.165          16.163   
4         19.141         12.370          14.578          17.849   

   measurement_12  measurement_13  measurement_14  measurement_15  \
0          13.772          13.659          16.825          13.742   
1          12.473          17.468          16.708          14.776   
2          10.907          13.363          15.737          17.065   
3          10.933          15.501          15.667          12.620   
4          11.941          16.070          16.183          13.324   

   measurement_16  measurement_17  
0          17.710         634.612  
1          14.102         537.037  
2          16.021         658.995  
3          16.111         594.301  
4          17.150         801.044  

[5 rows x 25 columns]

In [9]:
df.isnull().sum()

id                   0
product_code         0
loading            250
attribute_0          0
attribute_1          0
attribute_2          0
attribute_3          0
measurement_0        0
measurement_1        0
measurement_2        0
measurement_3      381
measurement_4      538
measurement_5      676
measurement_6      796
measurement_7      937
measurement_8     1048
measurement_9     1227
measurement_10    1300
measurement_11    1468
measurement_12    1601
measurement_13    1774
measurement_14    1874
measurement_15    2009
measurement_16    2110
measurement_17    2284
failure              0
dtype: int64

In [10]:
dt.isnull().sum()

id                   0
product_code         0
loading            223
attribute_0          0
attribute_1          0
attribute_2          0
attribute_3          0
measurement_0        0
measurement_1        0
measurement_2        0
measurement_3      329
measurement_4      409
measurement_5      508
measurement_6      624
measurement_7      720
measurement_8      846
measurement_9      904
measurement_10    1067
measurement_11    1136
measurement_12    1240
measurement_13    1303
measurement_14    1440
measurement_15    1542
measurement_16    1678
measurement_17    1740
dtype: int64

In [11]:
df.corr()

id   loading  attribute_2  attribute_3  measurement_0  \
id              1.000000  0.004305    -0.741200     0.558881      -0.253626   
loading         0.004305  1.000000    -0.008208    -0.000756      -0.005578   
attribute_2    -0.741200 -0.008208     1.000000    -0.538697       0.175387   
attribute_3     0.558881 -0.000756    -0.538697     1.000000      -0.370232   
measurement_0  -0.253626 -0.005578     0.175387    -0.370232       1.000000   
measurement_1   0.400206  0.002532    -0.377971     0.329233      -0.255255   
measurement_2   0.000128  0.000303     0.030522     0.013258      -0.083813   
measurement_3  -0.005923 -0.005203     0.005849    -0.002265      -0.004890   
measurement_4   0.011313 -0.011792    -0.011797     0.015470      -0.006459   
measurement_5  -0.007001 -0.005599     0.006811    -0.004034       0.003304   
measurement_6   0.008734  0.007310    -0.002181     0.000119       0.003731   
measurement_7  -0.011881 -0.001773     0.010338    -0.008046       0.000669   
measurement_8   0.000437 -0.002998    -0.001717    -0.006233      -0.005037   
measurement_9   0.001550 -0.007751    -0.000098    -0.002295       0.009112   
measurement_10 -0.029611 -0.007525    -0.004953    -0.100845       0.032779   
measurement_11  0.009524  0.003594     0.094038    -0.025434       0.001878   
measurement_12 -0.151220 -0.002407     0.226756    -0.132060       0.033496   
measurement_13 -0.037559  0.006138     0.049639     0.028472      -0.031527   
measurement_14 -0.053744  0.000120     0.020921    -0.049711       0.021907   
measurement_15  0.083951 -0.008087    -0.161242     0.187519      -0.055431   
measurement_16 -0.059849 -0.000633     0.035795    -0.061520       0.003025   
measurement_17 -0.000983  0.000305     0.004729    -0.001418       0.003351   
failure        -0.007545  0.129089     0.006337    -0.019222       0.009646   

                measurement_1  measurement_2  measurement_3  measurement_4  \
id                   0.400206       0.000128      -0.005923       0.011313   
loading              0.002532       0.000303      -0.005203      -0.011792   
attribute_2         -0.377971       0.030522       0.005849      -0.011797   
attribute_3          0.329233       0.013258      -0.002265       0.015470   
measurement_0       -0.255255      -0.083813      -0.004890      -0.006459   
measurement_1        1.000000       0.005032      -0.008363       0.001535   
measurement_2        0.005032       1.000000      -0.002751      -0.009797   
measurement_3       -0.008363      -0.002751       1.000000       0.009573   
measurement_4        0.001535      -0.009797       0.009573       1.000000   
measurement_5       -0.005587       0.000241       0.009864       0.005113   
measurement_6       -0.001562      -0.009157       0.008322       0.001682   
measurement_7       -0.016977       0.002012       0.006111      -0.004630   
measurement_8        0.000286       0.000591       0.001286       0.006374   
measurement_9        0.004529       0.001884       0.008195       0.009080   
measurement_10       0.011986       0.018695      -0.004854      -0.012998   
measurement_11      -0.035312      -0.003877      -0.004427      -0.002784   
measurement_12      -0.084605      -0.001808       0.002445      -0.002586   
measurement_13       0.007523       0.029145       0.005893      -0.002454   
measurement_14      -0.011471       0.014623       0.002150      -0.001713   
measurement_15       0.060870       0.000138      -0.010986      -0.004567   
measurement_16      -0.004509       0.033088      -0.002164       0.002929   
measurement_17      -0.004651      -0.009596       0.080902       0.193045   
failure             -0.010810       0.015808       0.003577      -0.010488   

                measurement_5  ...  measurement_9  measurement_10  \
id                  -0.007001  ...       0.001550       -0.029611   
loading             -0.005599  ...      -0.007751       -0.007525   
attribute_2          0.006811  ...      -0.00

In [12]:
df.nunique()

id                26570
product_code          5
loading           11950
attribute_0           2
attribute_1           3
attribute_2           4
attribute_3           4
measurement_0        29
measurement_1        30
measurement_2        25
measurement_3      4721
measurement_4      4692
measurement_5      4671
measurement_6      4704
measurement_7      4734
measurement_8      4713
measurement_9      4708
measurement_10     6177
measurement_11     6526
measurement_12     6392
measurement_13     5271
measurement_14     6389
measurement_15     6577
measurement_16     7035
measurement_17    23612
failure               2
dtype: int64

In [13]:
dt.nunique()

id                20775
product_code          4
loading           10741
attribute_0           2
attribute_1           3
attribute_2           3
attribute_3           4
measurement_0        30
measurement_1        33
measurement_2        28
measurement_3      4487
measurement_4      4514
measurement_5      4500
measurement_6      4476
measurement_7      4493
measurement_8      4513
measurement_9      4471
measurement_10     6217
measurement_11     6252
measurement_12     5623
measurement_13     5644
measurement_14     5795
measurement_15     6156
measurement_16     6396
measurement_17    18657
dtype: int64

In [14]:
df.shape

(26570, 26)

In [15]:
train_df = df.drop(labels = ["product_code","id","failure"],axis = 1)
test_dt = dt.drop(labels = ["product_code","id"],axis = 1)
y = df["failure"]

In [16]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: failure, dtype: int64

**Feature Engg**

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x_df = train_df.apply(le.fit_transform)
x_dt = test_dt.apply(le.fit_transform)
x_df.head()

loading  attribute_0  attribute_1  attribute_2  attribute_3  measurement_0  \
0     1325            1            2            3            0              7   
1     1722            1            2            3            0             14   
2     1524            1            2            3            0             12   
3     3190            1            2            3            0             13   
4    10266            1            2            3            0              9   

   measurement_1  measurement_2  measurement_3  measurement_4  ...  \
0              8              4           2613           3137  ...   
1              3              3           2786           2159  ...   
2              1              5           2630           2271  ...   
3              2              6           1868           1807  ...   
4              2              8           3914           3569  ...   

   measurement_8  measurement_9  measurement_10  measurement_11  \
0           3481           1576            2835            1751   
1           1215           3351            4909            2064   
2           1614           3616            2583            6526   
3           2386           3373            3322            2525   
4           1419           1241            4058            4077   

   measurement_12  measurement_13  measurement_14  measurement_15  \
0            6198            1930            6389            1299   
1            3279            1634            2599            2641   
2            5283            3611            5703            2340   
3            1548            2151            2736            4399   
4            3950            3083             331            1413   

   measurement_16  measurement_17  
0            1686           16441  
1            2629           10369  
2            4929            8902  
3            4164           19920  
4            3406            3854  

[5 rows x 23 columns]

In [18]:
from sklearn.impute import SimpleImputer
missing = SimpleImputer(missing_values=np.nan,strategy="median")
missing_df = missing.fit_transform(x_df)
missing_dt = missing.fit_transform(x_dt)
missing_df

array([[1.3250e+03, 1.0000e+00, 2.0000e+00, ..., 1.2990e+03, 1.6860e+03,
        1.6441e+04],
       [1.7220e+03, 1.0000e+00, 2.0000e+00, ..., 2.6410e+03, 2.6290e+03,
        1.0369e+04],
       [1.5240e+03, 1.0000e+00, 2.0000e+00, ..., 2.3400e+03, 4.9290e+03,
        8.9020e+03],
       ...,
       [4.5760e+03, 1.0000e+00, 1.0000e+00, ..., 3.8360e+03, 1.1160e+03,
        1.5486e+04],
       [3.6960e+03, 1.0000e+00, 1.0000e+00, ..., 1.8720e+03, 3.2300e+02,
        1.4002e+04],
       [6.0300e+03, 1.0000e+00, 1.0000e+00, ..., 4.7690e+03, 4.8740e+03,
        4.9720e+03]])

In [19]:
df_missing = pd.DataFrame(missing_df,index = train_df.index,columns = train_df.columns)
dt_missing = pd.DataFrame(missing_dt,index = test_dt.index,columns = test_dt.columns)
dt_missing.head()

loading  attribute_0  attribute_1  attribute_2  attribute_3  measurement_0  \
0   4585.0          0.0          1.0          0.0          0.0            6.0   
1   4022.0          0.0          1.0          0.0          0.0           11.0   
2   3899.0          0.0          1.0          0.0          0.0            8.0   
3   3950.0          0.0          1.0          0.0          0.0            8.0   
4  10022.0          0.0          1.0          0.0          0.0           14.0   

   measurement_1  measurement_2  measurement_3  measurement_4  ...  \
0            9.0            6.0         3743.0          725.0  ...   
1            8.0            0.0         2338.0         2451.0  ...   
2           12.0            4.0         2930.0         1010.0  ...   
3           11.0           10.0          983.0         1413.0  ...   
4           16.0            8.0         2263.0         3216.0  ...   

   measurement_8  measurement_9  measurement_10  measurement_11  \
0         1889.0         1620.0          2876.0          2323.0   
1         2603.0         2850.0          1051.0          6252.0   
2         1014.0         2561.0          4009.0          2338.0   
3         2183.0         2608.0          5063.0           582.0   
4         2376.0         3188.0          1569.0          2104.0   

   measurement_12  measurement_13  measurement_14  measurement_15  \
0          4656.0           832.0          3586.0          1634.0   
1          3402.0          4502.0          3469.0          2657.0   
2          1842.0           602.0          2501.0          4870.0   
3          1868.0          2579.0          2431.0           665.0   
4          2872.0          3148.0          2946.0          1245.0   

   measurement_16  measurement_17  
0          4306.0          5459.0  
1           883.0          1844.0  
2          2640.0          6794.0  
3          2730.0          3675.0  
4          3753.0         14689.0  

[5 rows x 23 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(df_missing)
ss.fit(dt_missing)
scaler_df = ss.transform(df_missing)
scaler_dt = ss.transform(dt_missing)
scaler_df

array([[-1.32848014,  1.0137162 ,  1.4384881 , ..., -1.21758056,
        -1.09217593,  1.10051585],
       [-1.18698738,  1.0137162 ,  1.4384881 , ..., -0.36557757,
        -0.52737552,  0.04449468],
       [-1.25755556,  1.0137162 ,  1.4384881 , ..., -0.55667511,
         0.85018644, -0.21064087],
       ...,
       [-0.16980768,  1.0137162 ,  0.01439516, ...,  0.39309872,
        -1.43357172,  0.93442556],
       [-0.48344403,  1.0137162 ,  0.01439516, ..., -0.85379687,
        -1.90853112,  0.67633343],
       [ 0.3484051 ,  1.0137162 ,  0.01439516, ...,  0.98543761,
         0.81724474, -0.89413283]])

In [21]:
df_scaler_df = pd.DataFrame(scaler_df,index=train_df.index,columns = train_df.columns)
dt_scaler_dt = pd.DataFrame(scaler_dt,index = test_dt.index,columns = test_dt.columns)
df_scaler_df

loading  attribute_0  attribute_1  attribute_2  attribute_3  \
0     -1.328480     1.013716     1.438488     2.103997    -1.310837   
1     -1.186987     1.013716     1.438488     2.103997    -1.310837   
2     -1.257556     1.013716     1.438488     2.103997    -1.310837   
3     -0.663785     1.013716     1.438488     2.103997    -1.310837   
4      1.858136     1.013716     1.438488     2.103997    -1.310837   
...         ...          ...          ...          ...          ...   
26565  1.209479     1.013716     0.014395    -0.282145     1.368135   
26566  0.829908     1.013716     0.014395    -0.282145     1.368135   
26567 -0.169808     1.013716     0.014395    -0.282145     1.368135   
26568 -0.483444     1.013716     0.014395    -0.282145     1.368135   
26569  0.348405     1.013716     0.014395    -0.282145     1.368135   

       measurement_0  measurement_1  measurement_2  measurement_3  \
0          -0.106093      -0.222062      -0.554549       0.331343   
1           1.531937      -1.375975      -0.815288       0.505862   
2           1.063928      -1.837540      -0.293810       0.348492   
3           1.297932      -1.606757      -0.033071      -0.420197   
4           0.361915      -1.606757       0.488407       1.643765   
...              ...            ...            ...            ...   
26565      -0.340097       1.624198      -0.554549      -1.419897   
26566       0.595920       0.701068       0.488407      -0.170020   
26567      -1.510119       0.239503      -1.336766      -1.961612   
26568      -1.276115       0.008720      -0.554549       0.350510   
26569      -0.340097       2.316546      -1.336766       0.325290   

       measurement_4  ...  measurement_8  measurement_9  measurement_10  \
0           0.835033  ...       1.078258      -0.728143       -0.272402   
1          -0.136987  ...      -1.097433       0.979781        1.075186   
2          -0.025672  ...      -0.714335       1.234767       -0.436139   
3          -0.486835  ...       0.026898       1.000949        0.044028   
4           1.264392  ...      -0.901563      -1.050484        0.522246   
...              ...  ...            ...            ...             ...   
26565       1.566533  ...       0.309181       2.285501       -2.035182   
26566       2.380526  ...       0.509852      -0.179683       -1.344494   
26567      -0.141956  ...       0.237170      -0.020918        0.103156   
26568       2.380526  ...       0.313022      -0.035352        0.510551   
26569      -0.245320  ...      -0.288990      -0.786838       -0.438738   

       measurement_11  measurement_12  measurement_13  measurement_14  \
0           -0.945299        2.340389       -0.770456        2.315716   
1           -0.748787        0.192906       -0.984773       -0.343718   
2            2.052612        1.667232        0.446664        1.834351   
3           -0.459355       -1.080575       -0.610442       -0.247586   
4            0.515045        0.686555        0.064368       -1.935168   
...               ...             ...             ...             ...   
26565       -0.732463       -1.013627       -0.215837        1.803476   
26566        0.909953       -0.924609       -1.188954       -1.110674   
26567       -1.015617       -1.890571       -0.741494        0.479373   
26568       -0.811571        2.274913        0.130256       -0.301616   
26569        0.371270       -0.358126       -0.157914       -1.694486   

       measurement_15  measurement_16  measurement_17  
0           -1.217581       -1.092176        1.100516  
1           -0.365578       -0.527376        0.044495  
2           -0.556675        0.850186       -0.210641  
3            0.750534        0.391997        1.705571  
4           -1.145205       -0.061999       -1.088572  
...               ...             ...             ...  
26565        0.744185        2.111554        0.665029  
26566       -1.149649       -0.027261        1.899488  
26567        0.393099       -1.433572       

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
pca.fit(df_scaler_df)
pca.fit(dt_scaler_dt)
pca_df = pca.transform(df_scaler_df)
pca_dt = pca.transform(dt_scaler_dt)
pca_df

array([[-0.19825849,  0.83397663, -1.45183295, ..., -0.73476565,
        -1.98096509,  0.69170554],
       [-0.6385079 , -0.86195068, -0.36293271, ...,  0.54417437,
        -0.1663876 ,  1.52015136],
       [-1.65453879,  0.46132331, -0.25692514, ...,  0.44542397,
        -0.78187884,  1.70623315],
       ...,
       [-1.28999028, -0.318196  , -0.65370217, ...,  0.29483959,
        -1.16474435, -1.24713788],
       [-0.70419794,  0.64148131, -1.7185629 , ...,  0.17434187,
        -1.15968845,  0.40954549],
       [-1.02892933, -0.1876542 ,  0.74335567, ..., -0.69032834,
         0.52576125,  0.54611872]])

In [23]:
x = pca_df

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 20,test_size = 0.3)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((18599, 10), (7971, 10), (18599,), (7971,))

In [25]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
pred = lr.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.7867268849579726

In [27]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(x_train,y_train)
final = dtr.predict(x_test)
final

array([0., 0., 0., ..., 0., 1., 1.])

In [28]:
accuracy_score(y_test,final)

0.6527411868021579

In [29]:
accuracy_score(y_train,dtr.predict(x_train))

1.0

In [30]:
accuracy_score(y_train,lr.predict(x_train))

0.7876767568148825

In [31]:
pred0 = dtr.predict(pca_dt)
pred0

array([0., 0., 1., ..., 0., 0., 0.])

In [32]:
pred1 = lr.predict(pca_dt)
pred1

array([0, 0, 0, ..., 0, 0, 0])

In [33]:
submission = pd.DataFrame({'ID':dt.id.values,'failure':pred1})
submission1 = pd.DataFrame({'ID':dt.id.values,'failure':pred0})

In [34]:
submission.head()

ID  failure
0  26570        0
1  26571        0
2  26572        0
3  26573        0
4  26574        0

In [35]:
submission1.head()

ID  failure
0  26570      0.0
1  26571      0.0
2  26572      1.0
3  26573      1.0
4  26574      1.0

In [36]:
submission["failure"].nunique()

1

In [37]:
submission.to_csv("Submission.csv",index = None)
submission1.to_csv("Submission1.csv",index =None)